daily-planner-ui/src/main/java/com/gl/training/dibrivnyi/planner/ui/controller/admin/AddUserController.java
package com.gl.training.dibrivnyi.planner.ui.controller.admin;

import com.gl.training.dibrivnyi.planner.user.model.User;
import com.gl.training.dibrivnyi.planner.user.service.api.AdministrationService;
import org.springframework.beans.factory.annotation.Autowired;

import javax.faces.application.FacesMessage;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;

/**
 * @author Alexandr Dibrivnyi
 *         11.08.14
 *         20:36
 */
@Named
@SessionScoped
public class AddUserController {

    @Autowired
    private AdministrationService administrationService;

    private User user;

    public User getUser() {
        if (user == null) {
            user = new User();
        }
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public void saveUser() {
        administrationService.addUser(user);
        user = null;

        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage("Successful", "User successfully added"));
    }
}

daily-planner-ui/src/main/java/com/gl/training/dibrivnyi/planner/ui/controller/admin/ListUsersController.java
package com.gl.training.dibrivnyi.planner.ui.controller.admin;

import com.gl.training.dibrivnyi.planner.user.model.User;
import com.gl.training.dibrivnyi.planner.user.service.api.AdministrationService;
import org.apache.commons.codec.digest.DigestUtils;
import org.primefaces.event.SelectEvent;
import org.springframework.beans.factory.annotation.Autowired;

import javax.faces.application.FacesMessage;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import java.util.List;

/**
 * @author Alexandr Dibrivnyi
 *         11.08.14
 *         22:25
 */
@Named
@SessionScoped
public class ListUsersController {

    @Autowired
    private AdministrationService administrationService;
    private User selectedUser;
    private boolean viewDetailsDisabled = true;

    public List<User> getAllUsers() {
        return administrationService.listAllUsers();
    }

    public User getSelectedUser() {
        return selectedUser;
    }

    public void setSelectedUser(User selectedUser) {
        this.selectedUser = selectedUser;
    }

    public boolean isViewDetailsDisabled() {
        return viewDetailsDisabled;
    }

    public void setViewDetailsDisabled(boolean viewDetailsDisabled) {
        this.viewDetailsDisabled = viewDetailsDisabled;
    }

    public void onRowSelect(SelectEvent event) {
        viewDetailsDisabled = false;
    }

    public void updateSelectedUser() {
        String notEncodedPassword = selectedUser.getPassword();
        selectedUser.setPassword(DigestUtils.sha1Hex(notEncodedPassword));
        administrationService.updateUser(selectedUser);

        FacesMessage msg = new FacesMessage();
        msg.setSeverity(FacesMessage.SEVERITY_INFO);
        msg.setSummary(String.format("User <%s> was updated", selectedUser.getLogin()));
        FacesContext.getCurrentInstance().addMessage(null, msg);

        selectedUser = null;
    }
}

daily-planner-ui/src/main/java/com/gl/training/dibrivnyi/planner/ui/controller/admin/SendMailController.java
package com.gl.training.dibrivnyi.planner.ui.controller.admin;

import com.gl.training.dibrivnyi.planner.user.service.api.MailService;
import org.springframework.beans.factory.annotation.Autowired;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ApplicationScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import java.util.List;

/**
 * @author Alexandr Dibrivnyi
 *         13.08.14
 *         12:23
 */
@Named
@ApplicationScoped
public class SendMailController {

    @Autowired
    private MailService mailService;
    private List<String> recipients;
    private String subject;
    private String description;

    public List<String> getRecipients() {
        return recipients;
    }

    public void setRecipients(List<String> recipients) {
        this.recipients = recipients;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void sendMessage() {
        mailService.sendEmail(recipients, subject, description);

        FacesMessage msg = new FacesMessage();
        msg.setSummary(String.format("Message with subject <%s> was sent to <%s> recipients", subject, recipients.size()));
        msg.setSeverity(FacesMessage.SEVERITY_INFO);

        FacesContext.getCurrentInstance().addMessage(null, msg);
        recipients = null;
        subject = null;
        description = null;
    }
}

daily-planner-ui/src/main/java/com/gl/training/dibrivnyi/planner/ui/controller/main/LoginController.java
package com.gl.training.dibrivnyi.planner.ui.controller.main;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.AuthenticationException;
import org.springframework.security.core.context.SecurityContextHolder;

import javax.faces.application.FacesMessage;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import java.util.logging.Logger;

/**
 * @author Alexandr Dibrivnyi
 *         15.08.14
 *         22:12
 */
@Named
@RequestScoped
public class LoginController {

    private static final Logger LOGGER = Logger.getLogger(LoginController.class.getSimpleName());
    @Autowired
    private AuthenticationManager authenticationManager;
    private String login;
    private String password;

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean performLogin() {
        boolean loginSuccessful;
        try {
            Authentication token = new UsernamePasswordAuthenticationToken(login, password);
            Authentication authentication = authenticationManager.authenticate(token);
            SecurityContextHolder.getContext().setAuthentication(authentication);
            loginSuccessful = true;
            LOGGER.info("Login successful. Navigating to plans view");
        } catch (AuthenticationException e) {
            String errorMessage = "Login or password is incorrect";
            FacesMessage msg = new FacesMessage();
            msg.setSeverity(FacesMessage.SEVERITY_WARN);
            msg.setSummary(errorMessage);

            FacesContext.getCurrentInstance().addMessage(null, msg);
            loginSuccessful = false;
            LOGGER.warning(errorMessage);
        }
        return loginSuccessful;
    }
}

daily-planner-ui/src/main/java/com/gl/training/dibrivnyi/planner/ui/controller/main/PlansController.java
package com.gl.training.dibrivnyi.planner.ui.controller.main;

import com.gl.training.dibrivnyi.planner.middle.exception.DuplicatedPlanException;
import com.gl.training.dibrivnyi.planner.middle.model.DailyPlan;
import com.gl.training.dibrivnyi.planner.middle.model.Task;
import com.gl.training.dibrivnyi.planner.middle.service.api.TaskService;
import com.gl.training.dibrivnyi.planner.middle.util.DateUtil;
import com.gl.training.dibrivnyi.planner.ui.api.Actions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.SecurityContextHolder;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import java.util.Date;
import java.util.List;

/**
 * @author Alexandr Dibrivnyi
 *         16.08.14
 *         21:50
 */
@Named
@SessionScoped
public class PlansController {

    @Autowired
    private TaskService taskService;
    @Autowired
    private DateUtil dateUtil;
    private Date dailyPlanDate;
    private DailyPlan selectedDailyPlan;
    private Task newTask;
    private List<Task> selectedTasks;

    @PostConstruct
    public void initController() {
        newTask = new Task();
        selectedDailyPlan = new DailyPlan();
    }

    public List<Task> getSelectedTasks() {
        return selectedTasks;
    }

    public void setSelectedTasks(List<Task> selectedTasks) {
        this.selectedTasks = selectedTasks;
    }

    public void removeSelectedTasks() {
        taskService.deleteTasks(selectedTasks);

        showMessage(String.format("Deleted <%s> tasks", selectedTasks.size()), FacesMessage.SEVERITY_INFO);
    }

    public Task firstSelectedTask() {
        return selectedTasks.get(0);
    }

    public Task getNewTask() {
        return newTask;
    }

    public void setNewTask(Task newTask) {
        this.newTask = newTask;
    }

    public DailyPlan getSelectedDailyPlan() {
        return selectedDailyPlan;
    }

    public void setSelectedDailyPlan(DailyPlan selectedDailyPlan) {
        this.selectedDailyPlan = selectedDailyPlan;
    }

    public Date getDailyPlanDate() {
        return dailyPlanDate;
    }

    public void setDailyPlanDate(Date dailyPlanDate) {
        this.dailyPlanDate = dailyPlanDate;
    }

    public List<DailyPlan> listAllDailyPlansForCurrentUser() {
        String login = SecurityContextHolder.getContext().getAuthentication().getName();
        return taskService.findAllDailyPlansForUser(login);
    }

    public void createDailyPlan() {
        if (dailyPlanDate == null) {
            showMessage("Please select date first", FacesMessage.SEVERITY_WARN);
        } else if (dateUtil.isDayBefore(dailyPlanDate)) {
            showMessage("Date should be modern", FacesMessage.SEVERITY_WARN);
        } else {
            String login = SecurityContextHolder.getContext().getAuthentication().getName();
            try {
                taskService.createDailyPlan(dailyPlanDate, login);
                showMessage("Daily plan was created", FacesMessage.SEVERITY_INFO);
            } catch (DuplicatedPlanException e) {
                showMessage(e.getMessage(), FacesMessage.SEVERITY_WARN);
            }
        }
    }

    public String showDailyPlan() {
        return Actions.SUCCESS;
    }

    public void addTaskToDailyPlan() {
        if (newTask.getEndTime().before(newTask.getStartTime())) {
            showMessage("End time should be after start time", FacesMessage.SEVERITY_WARN);
        } else {
            taskService.addTaskToDailyPlan(newTask, selectedDailyPlan);
            showMessage("Task was added successfully", FacesMessage.SEVERITY_INFO);
            newTask = null;
        }
    }

    private void showMessage(String description, FacesMessage.Severity severity) {
        FacesMessage facesMessage = new FacesMessage();
        facesMessage.setSeverity(severity);
        facesMessage.setSummary(description);

        FacesContext.getCurrentInstance().addMessage(null, facesMessage);
    }
}

daily-planner-ui/src/main/webapp/admin_users.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:custom="http://java.sun.com/jsf/composite/admin"
        >
<h:head>
    <h:outputStylesheet library="css" name="bootstrap.css"/>
    <title>Users management</title>
</h:head>
<h:body>
    <div class="container">
        <div class="navbar-form navbar-left">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#">Users management</a></li>
            </ul>
        </div>
        <div class="navbar-form navbar-right">
            <ul class="nav nav-tabs ">
                <li><a href="logout">Logout</a></li>
            </ul>
        </div>
    </div>
    <div class="container ui-grid ui-grid-responsive">
        <p:accordionPanel>
            <div class="ui-grid-row">
                <p:tab title="Add user">
                    <custom:addUserComponent userLoginValue="#{addUserController.user.login}"
                                             userEmailValue="#{addUserController.user.email}"
                                             userPasswordValue="#{addUserController.user.password}"
                                             userFirstNameValue="#{addUserController.user.firstName}"
                                             userLastNameValue="#{addUserController.user.lastName}"
                                             userDateOfBirthValue="#{addUserController.user.dateOfBirth}"
                                             saveAction="#{addUserController.saveUser}"/>
                </p:tab>
            </div>
            <div class="ui-grid-row">
                <p:tab title="View users">
                    <h:panelGrid columns="2" cellpadding="10">
                        <custom:listAllUsersComponent usersValue="#{listUsersController.allUsers}"/>
                    </h:panelGrid>
                </p:tab>
            </div>
            <div class="ui-grid-row">
                <p:tab title="Send a group email">
                    <custom:sendGroupEmailComponent recipients="#{sendMailController.recipients}"
                                                    description="#{sendMailController.description}"
                                                    subject="#{sendMailController.subject}"
                                                    users="#{listUsersController.allUsers}"
                                                    sendMessage="#{sendMailController.sendMessage}"/>
                </p:tab>
            </div>
        </p:accordionPanel>
    </div>
</h:body>
</html>

daily-planner-ui/src/main/webapp/main_index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
<h:head>
    <h:outputStylesheet library="css" name="bootstrap.css"/>
    <title>Daily planner</title>
</h:head>
<h:body>
    <h:form>
        <div class="container">
            <div class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="#">Daily planner</a>
                    </div>
                </div>
            </div>
            <div class="jumbotron">
                <h1 class="center">Daily planner</h1>

                <p class="lead center">
                    Daily Planner is a to-do list that helps you arrange the current, daily, weekly tasks.
                </p>
                <h:button outcome="main_signin" immediate="true" styleClass="btn-lg btn-primary" value="Sign in"/>
            </div>
        </div>
    </h:form>
</h:body>
</html>

daily-planner-ui/src/main/webapp/main_plans.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:component="http://java.sun.com/jsf/composite/main"
      xmlns:f="http://java.sun.com/jsf/core">
<h:head>
    <h:outputStylesheet library="css" name="bootstrap.css"/>
    <title>Daily planner</title>
</h:head>
<h:body>
    <div class="container">
        <component:pageHeader/>
        <h:form>
            <p:growl id="msgs" showDetail="true" sticky="true"/>

            <p:panel id="addPlanPanel"
                     header="Add daily plan"
                     toggleable="true"
                     closable="true"
                     toggleSpeed="500"
                     closeSpeed="500"
                     widgetVar="addPlanPanel"
                     style="margin-bottom:20px">
                <p>
                    <h:panelGrid columns="1"
                                 cellpadding="10">
                        <p:calendar placeholder="Select daily plan date"
                                    value="#{plansController.dailyPlanDate}"
                                    mode="inline"/>
                    </h:panelGrid>
                </p>

                <p>
                    <p:commandButton value="Create daily plan"
                                     actionListener="#{plansController.createDailyPlan}"
                                     update=":#{p:component('addPlanPanel')}, :#{p:component('msgs')}, :#{p:component('dailyPlansListScroller')}"/>
                </p>

            </p:panel>
        </h:form>
        <h:form id="dailyPlansListForm">
            <p:dataScroller id="dailyPlansListScroller"
                            value="#{plansController.listAllDailyPlansForCurrentUser()}"
                            var="dailyPlan"
                            chunkSize="10">
                <f:facet name="header">
                    Scroll Down to Load Daily Plans. Click to see details
                </f:facet>

                <h:panelGrid columns="1" style="width:100%" columnClasses="date">
                    <p:outputPanel>
                        <h:panelGrid columns="1" cellpadding="5">
                            <p>
                                <h:commandLink value="${dailyPlan.date}"
                                               action="#{plansController.showDailyPlan}">
                                    <f:setPropertyActionListener value="#{dailyPlan}"
                                                                 target="#{plansController.selectedDailyPlan}"/>
                                </h:commandLink>
                            </p>
                        </h:panelGrid>
                    </p:outputPanel>
                </h:panelGrid>
            </p:dataScroller>
        </h:form>
    </div>
</h:body>
</html>

daily-planner-ui/src/main/webapp/main_signin.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui" xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:h="http://java.sun.com/jsf/html"
        >
<h:head>
    <title>Sign in</title>
    <h:outputStylesheet library="css" name="signin.css"/>
    <h:outputStylesheet library="css" name="bootstrap.css"/>
</h:head>
<h:body>
    <div class="container" style="width: 300px">
        <h:form>
            <p:panel id="panel" header="Sign in" styleClass="form-signin">
                <p:growl id="msgs"/>
                <p:panelGrid columns="1"
                             cellpadding="5">
                    <p:inputText id="login"
                                 placeholder="Login"
                                 value="#{loginController.login}"
                                 required="true"
                                 label="Login">
                        <f:validateLength minimum="3"/>
                    </p:inputText>

                    <p:password id="password" value="#{loginController.password}"
                                placeholder="Password"
                                required="true"
                                label="Passwprd">
                        <f:validateLength minimum="3"/>
                    </p:password>

                    <p:commandButton value="Login"
                                     update="panel"
                                     action="#{loginController.performLogin()}"
                                     icon="ui-icon-check"/>
                </p:panelGrid>
            </p:panel>
        </h:form>
    </div>
</h:body>
</html>

daily-planner-ui/src/main/webapp/main_view_plan.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:p="http://primefaces.org/ui"
      xmlns:component="http://java.sun.com/jsf/composite/main"
      xmlns:c="http://java.sun.com/jsp/jstl/core">
<h:head>
    <h:outputStylesheet library="css" name="bootstrap.css"/>
    <title>Daily planner</title>
</h:head>
<h:body>
    <c:set var="canEditTask" value="#{plansController.selectedDailyPlan.state == 'OPENED'}"/>
    <p:growl autoUpdate="true"/>

    <div class="container">
        <component:pageHeader/>
        <c:if test="#{canEditTask}">
            <h:form id="addTaskForm">
                <p:panel>
                    <f:facet name="header">
                        Add task
                    </f:facet>
                    <h:panelGrid columns="1" style="width: 100%" cellpadding="10" id="grid">
                        <h:outputLabel value="Title"
                                       for="titleInput"/>
                        <h:inputText id="titleInput"
                                     value="#{plansController.newTask.title}"
                                     required="true">
                            <f:validateLength minimum="3"/>
                        </h:inputText>
                        <h:outputLabel value="Description"
                                       for="descriptionInput"/>
                        <h:inputTextarea id="descriptionInput"
                                         value="#{plansController.newTask.description}"
                                         required="true">
                            <f:validateLength minimum="3"/>
                        </h:inputTextarea>
                        <h:outputLabel value="Start date"
                                       for="startInput"/>
                        <p:calendar id="startInput"
                                    value="#{plansController.newTask.startTime}"
                                    pattern="HH:mm a"
                                    timeOnly="true"
                                    required="true"/>
                        <h:outputLabel value="End date"
                                       for="endInput"/>
                        <p:calendar id="endInput"
                                    value="#{plansController.newTask.endTime}"
                                    pattern="HH:mm a"
                                    required="true"
                                    timeOnly="true"/>
                    </h:panelGrid>
                    <f:facet name="footer">
                        <h:commandButton value="Add task" action="#{plansController.addTaskToDailyPlan}"
                                         update=":#{p:component('planViewForm')}, :#{p:component('addTaskForm')}, :#{p:component('grid')}"/>
                    </f:facet>
                </p:panel>
            </h:form>
            <p:separator/>
        </c:if>
        <h:form id="planViewForm">
            <p:dataTable id="tasksTable"
                         var="task"
                         value="#{plansController.selectedDailyPlan.dayTasks}"
                         selection="#{plansController.selectedTasks}"
                         rowKey="#{task.id}"
                         style="margin-bottom:0">
                <f:facet name="header">
                    Tasks
                </f:facet>
                <p:column selectionMode="multiple" style="width:35px;text-align:center"/>
                <p:column headerText="Title">
                    <h:outputText value="#{task.title}"/>
                </p:column>
                <p:column headerText="Description">
                    <h:outputText value="#{task.description}"/>
                </p:column>
                <p:column headerText="Start time">
                    <h:outputText value="#{task.startTime}"/>
                </p:column>
                <p:column headerText="End time">
                    <h:outputText value="#{task.endTime}"/>
                </p:column>
                <f:facet name="footer">
                    <c:if test="#{canEditTask}">
                        <p:commandButton process="tasksTable"
                                         update=":#{p:component('planViewForm')}, :#{p:component('tasksTable')}"
                                         actionListener="#{plansController.removeSelectedTasks}"
                                         value="Remove"/>
                    </c:if>
                </f:facet>
            </p:dataTable>
        </h:form>
        <p:separator/>
        <h:form>
            <p:panel>
                <f:facet name="header">
                    <h:button value="Back" outcome="main_plans"/>
                </f:facet>
            </p:panel>
        </h:form>
    </div>
</h:body>
</html>